version: '3.5'
services:
  backup:
    image: autorestic:${AUTORESTIC_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=$http_proxy
        - https_proxy=$https_proxy
        - no_proxy=$no_proxy
